// GENERATED from the Q3-2026 mobile reception schedule (jadval.md) —
// regenerate with the generator script rather than editing rows by hand.
import 'package:flutter/material.dart';

import 'l10n.dart';

/// One mobile (field) reception stop: the district/city it belongs to, the
/// date and the venue (usually an MFY — citizens' assembly). Place names are
/// carried in Uzbek Latin plus the source's Cyrillic, shown for Russian.
class SayyorVisit {
  const SayyorVisit(
      this.region, this.regionRu, this.date, this.place, this.placeRu);

  final String region;
  final String regionRu;

  /// `dd.mm.yyyy`, or an Uzbek month name ('Iyul') when the source schedule
  /// gave only the month. Render through [SayyorData.localizeDate].
  final String date;
  final String place;
  final String placeRu;

  /// District/city name in the kiosk language.
  String regionFor(Lang lang) {
    if (lang == Lang.ru) return regionRu;
    if (lang == Lang.en && region == 'Viloyat tashkilotlari') {
      return 'Regional organisations';
    }
    return region;
  }

  /// Venue (MFY) name in the kiosk language's script.
  String placeFor(Lang lang) => lang == Lang.ru ? placeRu : place;
}

/// An organisation holding mobile receptions across the region.
class SayyorOrg {
  const SayyorOrg(this.name, this.icon, this.visits);

  final Map<Lang, String> name;
  final IconData icon;
  final List<SayyorVisit> visits;
}

/// The Tashkent region Q3-2026 mobile reception schedule, grouped by
/// organisation (largest first), each visit sorted chronologically.
class SayyorData {
  const SayyorData._();

  static const Map<Lang, List<String>> _months = {
    Lang.uz: ['Iyul', 'Avgust', 'Sentabr'],
    Lang.ru: ['Июль', 'Август', 'Сентябрь'],
    Lang.en: ['July', 'August', 'September'],
  };

  /// dd.mm.yyyy dates pass through; bare month names are localised.
  static String localizeDate(String date, Lang lang) {
    final i = _months[Lang.uz]!.indexOf(date);
    return i == -1 ? date : _months[lang]![i];
  }

  static const List<SayyorOrg> orgs = [
    SayyorOrg({
      Lang.uz: "Ijtimoiy himoya",
      Lang.ru: "Социальная защита",
      Lang.en: "Social protection",
    }, Icons.volunteer_activism_outlined, [
      SayyorVisit("Parkent tumani", "Паркентский район", "22.07.2026", "Samsarak MFY", "Самсарак МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "22.07.2026", "Oppoq MFY", "Оппоқ МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "22.07.2026", "Xuvaydo MFY", "Хувайдо МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "23.07.2026", "Turkiston MFY", "Туркистон МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "23.07.2026", "Namuna MFY", "Намуна МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "23.07.2026", "Tong yulduzi MFY", "Тонг юлдузи МФЙ"),
      SayyorVisit("Yangiyo'l shahri", "город Янгиюль", "23.07.2026", "Baxor, Baxt MFY", "Бахор, Бахт МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "24.07.2026", "Chetsuv MFY", "Четсув МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "24.07.2026", "Iskandar MFY", "Искандар МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "24.07.2026", "Quyun MFY", "Қуюн МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "24.07.2026", "Tut MFY", "Тут МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "24.07.2026", "A.Temur, Baxor, Madaniyat MFY", "А.Темур, Бахор, Маданият МФЙ"),
      SayyorVisit("O'rta Chirchiq tumani", "Уртачирчикский район", "24.07.2026", "Yoriq, Qunduzak, Darxan MFY", "Ёриқ, Қундузак, Дархан МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "24.07.2026", "Iloq MFY", "Илоқ МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "24.07.2026", "Mevazor MFY", "Мевазор МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "25.07.2026", "Mustaqillik MFY", "Мустақиллик МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "26.07.2026", "Uzumzor MFY", "Узумзор МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "27.07.2026", "Navbaxor MFY", "Навбахор МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "28.07.2026", "Chinoz tumani", "Чиназский район"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "28.07.2026", "Eshonobod MFY", "Эшонобод МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "28.07.2026", "Sakson ota MFY", "Саксон ота МФЙ"),
      SayyorVisit("Bekobod tumani", "Бекабадский район", "28.07.2026", "Nayman MFY", "Найман МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "29.07.2026", "Fayzobod MFY", "Файзобод МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "30.07.2026", "Obod to'qimachi MFY", "Обод тўқимачи МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "30.07.2026", "Oqtepa MFY", "Оқтепа МФЙ"),
      SayyorVisit("Olmaliq shahar", "город Алмалык", "30.07.2026", "Cho'lpon, Kimyogar MFY", "Чўлпон, Кимёгар МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "30.07.2026", "Pargos MFY", "Паргос МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "30.07.2026", "Uymavut MFY", "Уймавут МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "02.08.2026", "O'nqo'rg'on MFY", "Ўнқўрғон МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "04.08.2026", "Ramadon MFY", "Рамадон МФЙ"),
      SayyorVisit("Bekobod tumani", "Бекабадский район", "04.08.2026", "Oq tepa MFY", "Оқ тепа МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "04.08.2026", "Qo'rsoy MFY", "Қўрсой МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "04.08.2026", "G'ayrat MFY", "Ғайрат МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "05.08.2026", "Oqibat MFY", "Оқибат МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "05.08.2026", "Qo'lichi MFY", "Қўличи МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "06.08.2026", "Obod, Bunyodkor MFY", "Обод, Бунёдкор МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "07.08.2026", "Yoshlik MFY", "Ёшлик МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "07.08.2026", "Ittifoq, Sho'ralisoy, Markaziy MFY", "Иттифоқ, Шўралисой, Марказий МФЙ"),
      SayyorVisit("Bekobod tumani", "Бекабадский район", "07.08.2026", "Paxtakor MFY", "Пахтакор МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "07.08.2026", "Istiqlol MFY", "Истиқлол МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "07.08.2026", "O'tkir MFY", "Ўткир МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "07.08.2026", "Saxovat MFY", "Саховат МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "08.08.2026", "Chirchiq shahar", "город Чирчик"),
      SayyorVisit("Angren shahar", "город Ангрен", "10.08.2026", "Oppartak MFY", "Оппартак МФЙ"),
      SayyorVisit("Bekobod tumani", "Бекабадский район", "11.08.2026", "Pastki kerait MFY", "Пастки кераит МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "11.08.2026", "Buloqboshi MFY", "Булоқбоши МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "11.08.2026", "Fayzobod MFY", "Файзобод МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "11.08.2026", "Tarnov MFY", "Тарнов МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "12.08.2026", "Kanalobod MFY", "Каналобод МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "12.08.2026", "Qizg'aldoq MFY", "Қизғалдоқ МФЙ"),
      SayyorVisit("Bekobod shahar", "город Бекабад", "12.08.2026", "Navro'z MFY", "Наврўз МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "13.08.2026", "Xosildor, Navbaxor MFY", "Хосилдор, Навбахор МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "13.08.2026", "Oybek MFY", "Ойбек МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "14.08.2026", "Yuqori Chirchiq tumani", "Юкоричирчикский район"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "14.08.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "14.08.2026", "Katta ravot MFY", "Катта равот МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "14.08.2026", "To'qimachi MFY", "Тўқимачи МФЙ"),
      SayyorVisit("Bekobod tumani", "Бекабадский район", "14.08.2026", "Taqachi MFY", "Тақачи МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "14.08.2026", "Ko'k to'nli, S.Xondoyliqiy MFY", "Кўк тўнли, С.Хондойлиқий МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "15.08.2026", "Mir Alisher MFY", "Мир Алишер МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "15.08.2026", "Taraqqiyot MFY", "Тараққиёт МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "15.08.2026", "Farovon MFY", "Фаровон МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "17.08.2026", "Turopobod MFY", "Туропобод МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "17.08.2026", "O'rta Chirchiq tumani", "Уртачирчикский район"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "18.08.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "18.08.2026", "Qang'li MFY", "Қанғли МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "18.08.2026", "Ko'tarma MFY", "Кўтарма МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "19.08.2026", "A.Navoiy MFY", "А.Навоий МФЙ"),
      SayyorVisit("Quyi Chirchiq tumani", "Куйичирчикский район", "19.08.2026", "Yulduz MFY", "Юлдуз МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "19.08.2026", "Boyqozon MFY", "Бойқозон МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "20.08.2026", "Ko'ksaroy MFY", "Кўксарой МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "20.08.2026", "Chinor MFY", "Чинор МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "20.08.2026", "Yoshlik, Tovoqsoy MFY", "Ёшлик, Товоқсой МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "21.08.2026", "Xarakat MFY", "Харакат МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "21.08.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "21.08.2026", "Novobod MFY", "Новобод МФЙ"),
      SayyorVisit("Bekobod tumani", "Бекабадский район", "21.08.2026", "O'zbekiston MFY", "Ўзбекистон МФЙ"),
      SayyorVisit("O'rta Chirchiq tumani", "Уртачирчикский район", "21.08.2026", "Jarg'aboy, Yangilik, Beshboy, Galabotir MFY", "Жарғабой, Янгилик, Бешбой, Галаботир МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "22.08.2026", "Xaydarobod MFY", "Хайдаробод МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "22.08.2026", "Do'ngqo'rg'on MFY", "Дўнгқўрғон МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "24.08.2026", "Yangiyo'l tumani", "Янгиюльский район"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "24.08.2026", "Shodlik MFY", "Шодлик МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "25.08.2026", "Nurli zamin MFY", "Нурли замин МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "25.08.2026", "Sog'lom MFY", "Соғлом МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "26.08.2026", "Bunyodkor MFY", "Бунёдкор МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "26.08.2026", "Islomobod MFY", "Исломобод МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "27.08.2026", "Xo'ja MFY", "Хўжа МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "27.08.2026", "Achchisay MFY", "Аччисай МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "28.08.2026", "Yangiyo'l, Vatan, Iftixor MFY", "Янгийўл, Ватан, Ифтихор МФЙ"),
      SayyorVisit("Bekobod tumani", "Бекабадский район", "28.08.2026", "O'zbekobod MFY", "Ўзбекобод МФЙ"),
      SayyorVisit("Bekobod shahar", "город Бекабад", "28.08.2026", "Farxod, Tsementchi MFY", "Фарход, Цементчи МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "29.08.2026", "Barraj MFY", "Барраж МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "01.09.2026", "Xosildor MFY", "Хосилдор МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "02.09.2026", "Uchchinor MFY", "Уччинор МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "04.09.2026", "Rovot MFY", "Ровот МФЙ"),
      SayyorVisit("Bekobod tumani", "Бекабадский район", "04.09.2026", "O'rikzor MFY", "Ўрикзор МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "04.09.2026", "Extirom MFY", "Эхтиром МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "04.09.2026", "Quyosh, Lola MFY", "Қуёш, Лола МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "05.09.2026", "Bog'chaovul MFY", "Боғчаовул МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "07.09.2026", "Saxovat MFY", "Саховат МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "07.09.2026", "Soy MFY", "Сой МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "07.09.2026", "Bodomzor MFY", "Бодомзор МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "08.09.2026", "Dexqonobod MFY", "Дехқонобод МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "09.09.2026", "Chinmaschit MFY", "Чинмасчит МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "09.09.2026", "Xalimkop MFY", "Халимкоп МФЙ"),
      SayyorVisit("Yangiyo'l shahri", "город Янгиюль", "10.09.2026", "Navro'z, Me'zon MFY", "Наврўз, Меъзон МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "10.09.2026", "Yangiyo'l shahar", "город Янгиюль"),
      SayyorVisit("Bekobod tumani", "Бекабадский район", "11.09.2026", "Uyas MFY", "Уяс МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "11.09.2026", "Dexqonobod MFY", "Дехқонобод МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "11.09.2026", "Tolebi MFY", "Толеби МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "11.09.2026", "Jag'albayli MFY", "Жағалбайли МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "12.09.2026", "Fayzobod MFY", "Файзобод МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "14.09.2026", "Nurobod MFY", "Нуробод МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "15.09.2026", "Xo'jaqo'rg'on MFY", "Хўжақўрғон МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "15.09.2026", "Qizil soy MFY", "Қизил сой МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "15.09.2026", "Yangi go'shtsoy MFY", "Янги гўштсой МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "16.09.2026", "Majnuntol MFY", "Мажнунтол МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "17.09.2026", "Yollama MFY", "Ёллама МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "17.09.2026", "Bo'rsiliq MFY", "Бўрсилиқ МФЙ"),
      SayyorVisit("Quyi Chirchiq tumani", "Куйичирчикский район", "17.09.2026", "Jumag'ul MFY", "Жумағул МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "18.09.2026", "Shodlik MFY", "Шодлик МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "18.09.2026", "Qorasuvyoqa MFY", "Қорасувёқа МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "18.09.2026", "Iftixor MFY", "Ифтихор МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "18.09.2026", "Sanam MFY", "Санам МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "18.09.2026", "Qiziloy MFY", "Қизилой МФЙ"),
      SayyorVisit("Bekobod shahar", "город Бекабад", "18.09.2026", "Taraqqiyot, X.Olimjon MFY", "Тараққиёт, Х.Олимжон МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "18.09.2026", "Yangixayot MFY", "Янгихаёт МФЙ"),
      SayyorVisit("O'rta Chirchiq tumani", "Уртачирчикский район", "18.09.2026", "Taraqqiyot, Yangiyo'l, Xalqobod, Uyg'ur MFY", "Тараққиёт, Янгийўл, Халқобод, Уйғур МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "18.09.2026", "Zarafshon MFY", "Зарафшон МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "18.09.2026", "Mingbuloq, M.Ulug'bek, Ibrat MFY", "Мингбулоқ, М.Улуғбек, Ибрат МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "18.09.2026", "Qoraquduq MFY", "Қорақудуқ МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "19.09.2026", "Boladala MFY", "Боладала МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "22.09.2026", "Soxibkor MFY", "Сохибкор МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "22.09.2026", "Chinobod MFY", "Чинобод МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "22.09.2026", "Qo'shshukur MFY", "Қўшшукур МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "22.09.2026", "Nurli yo'l MFY", "Нурли йўл МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "23.09.2026", "Zargar MFY", "Заргар МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "23.09.2026", "Degantepa MFY", "Дегантепа МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "23.09.2026", "Qaxramon MFY", "Қахрамон МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "25.09.2026", "Novobod MFY", "Новобод МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "25.09.2026", "Qoraqo'yli MFY", "Қорақўйли МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "25.09.2026", "Kamolot MFY", "Камолот МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "26.09.2026", "G'ayrat MFY", "Ғайрат МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "28.09.2026", "Quruqsoy MFY", "Қуруқсой МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "29.09.2026", "Jumabozor MFY", "Жумабозор МФЙ"),
      SayyorVisit("Quyi Chirchiq tumani", "Куйичирчикский район", "29.09.2026", "Paxtachi MFY", "Пахтачи МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "29.09.2026", "Dexqonobod MFY", "Дехқонобод МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "30.09.2026", "Kalas MFY", "Калас МФЙ"),
      SayyorVisit("Zangiota tumani", "Зангиатинский район", "30.09.2026", "Quyoshli MFY", "Қуёшли МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Pensiya jamg'armasi",
      Lang.ru: "Пенсионный фонд",
      Lang.en: "Pension Fund",
    }, Icons.savings_outlined, [
      SayyorVisit("Chinoz tumani", "Чиназский район", "22.07.2026", "Navro'z MFY", "Наврўз МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "23.07.2026", "Guliston MFY", "Гулистон МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "23.07.2026", "Kimyogar, Adolat, Shodlik MFY", "Кимёгар, Адолат, Шодлик МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "23.07.2026", "Guliston MFY", "Гулистон МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "24.07.2026", "Baxmal MFY", "Бахмал МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "24.07.2026", "Nurobod MFY", "Нуробод МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "28.07.2026", "Guliston MFY", "Гулистон МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "29.07.2026", "Obod MFY", "Обод МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "31.07.2026", "Xalqobod MFY", "Халқобод МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "03.08.2026", "Oydin MFY", "Ойдин МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "04.08.2026", "Namuna, Qorabog' MFY", "Намуна, Қорабоғ МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "06.08.2026", "Navro'z 1 MFY", "Наврўз 1 МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "06.08.2026", "Rovot MFY", "Ровот МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "07.08.2026", "Olmazor, Mirishkor MFY", "Олмазор, Миришкор МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "10.08.2026", "Go'shtsoy MFY", "Гўштсой МФЙ"),
      SayyorVisit("Quyi Chirchiq tumani", "Куйичирчикский район", "11.08.2026", "To'qboy MFY", "Тўқбой МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "11.08.2026", "Navbaxor MFY", "Навбахор МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "11.08.2026", "A.Temur, Madaniyat, Baxt MFY", "А.Темур, Маданият, Бахт МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "12.08.2026", "Ko'lota MFY", "Кўлота МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "12.08.2026", "Qirariq MFY", "Қирариқ МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "13.08.2026", "O'ratepa MFY", "Ўратепа МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "13.08.2026", "Xonobod MFY", "Хонобод МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "14.08.2026", "Markaziy MFY", "Марказий МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "14.08.2026", "Nixol MFY", "Нихол МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "15.08.2026", "Tolbuloq MFY", "Толбулоқ МФЙ"),
      SayyorVisit("Bekobod tumani", "Бекабадский район", "18.08.2026", "Yoshlik, Xos, Istiqlol MFY", "Ёшлик, Хос, Истиқлол МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "18.08.2026", "To'y tepa MFY", "Тўй тепа МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "19.08.2026", "Bunyodkor MFY", "Бунёдкор МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "19.08.2026", "A.Temur MFY", "А.Темур МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "20.08.2026", "Novobod MFY", "Новобод МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "20.08.2026", "Adolat MFY", "Адолат МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "21.08.2026", "Vatan MFY", "Ватан МФЙ"),
      SayyorVisit("Yangiyo'l shahri", "город Янгиюль", "21.08.2026", "Ramadon MFY", "Рамадон МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "26.08.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "28.08.2026", "Iftixor, Pistalik MFY", "Ифтихор, Писталик МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "03.09.2026", "Qo'lichi MFY", "Қўличи МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "08.09.2026", "Yoshlik MFY", "Ёшлик МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "09.09.2026", "Dashtobod MFY", "Даштобод МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "09.09.2026", "Ma'rifat, Xamza, Navro'z MFY", "Маърифат, Хамза, Наврўз МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "10.09.2026", "Iloq MFY", "Илоқ МФЙ"),
      SayyorVisit("Quyi Chirchiq tumani", "Куйичирчикский район", "10.09.2026", "Ko'ksaroy MFY", "Кўксарой МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "11.09.2026", "Darxon, Qovunchi MFY", "Дархон, Қовунчи МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "11.09.2026", "Sanoat MFY", "Саноат МФЙ"),
      SayyorVisit("Parkent tumani", "Паркентский район", "11.09.2026", "Mozorxoji MFY", "Мозорхожи МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "14.09.2026", "Chuvildoq MFY", "Чувилдоқ МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "14.09.2026", "Obliq, Yangigo'shtsoy MFY", "Облиқ, Янгигўштсой МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "15.09.2026", "Suvti MFY", "Сувти МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "15.09.2026", "Muqimiy, Evalak MFY", "Муқимий, Эвалак МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "15.09.2026", "Geolog, Gulbog' MFY", "Геолог, Гулбоғ МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "16.09.2026", "Achamayli MFY", "Ачамайли МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "17.09.2026", "G'ayrat MFY", "Ғайрат МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "17.09.2026", "Do'stlik MFY", "Дўстлик МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "18.09.2026", "Yoshlik, Shodlik MFY", "Ёшлик, Шодлик МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "18.09.2026", "Do'stlik MFY", "Дўстлик МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "18.09.2026", "Qorasuv MFY", "Қорасув МФЙ"),
      SayyorVisit("Bekobod tumani", "Бекабадский район", "19.09.2026", "Oltin vodiy, Yoshlik-2, Bobur Mirzo MFY", "Олтин водий, Ёшлик-2, Бобур Мирзо МФЙ"),
      SayyorVisit("Qibray tumani", "Кибрайский район", "22.09.2026", "Mexnat MFY", "Мехнат МФЙ"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "23.09.2026", "Qo'raqo'yli MFY", "Қўрақўйли МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "25.09.2026", "Saxovat, Axil MFY", "Саховат, Ахил МФЙ"),
      SayyorVisit("Yangiyo'l shahri", "город Янгиюль", "25.09.2026", "Fayzobod MFY", "Файзобод МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Moliya",
      Lang.ru: "Финансы",
      Lang.en: "Finance",
    }, Icons.payments_outlined, [
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "23.07.2026", "Bo'stonliq tumani", "Бостанлыкский район"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "23.07.2026", "Mustaqillik MFY", "Мустақиллик МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "23.07.2026", "Mingtepa MFY", "Мингтепа МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "24.07.2026", "Sog'lom MFY", "Соғлом МФЙ"),
      SayyorVisit("Quyi Chirchiq tumani", "Куйичирчикский район", "14.08.2026", "Mashrab MFY", "Машраб МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "18.08.2026", "Tinchlik MFY", "Тинчлик МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "20.08.2026", "Bekobod shahar", "город Бекабад"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "20.08.2026", "S.Segizboyev MFY", "С.Сегизбоев МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "20.08.2026", "Bekobod MFY", "Бекобод МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "28.08.2026", "Mustaqillik MFY", "Мустақиллик МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "10.09.2026", "Parkent tumani", "Паркентский район"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "10.09.2026", "Boyg'uli MFY", "Бойғули МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "10.09.2026", "Oybek MFY", "Ойбек МФЙ"),
      SayyorVisit("Quyi Chirchiq tumani", "Куйичирчикский район", "18.09.2026", "Bog'iston MFY", "Боғистон МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "22.09.2026", "Shodlik MFY", "Шодлик МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "25.09.2026", "Kimyogar MFY", "Кимёгар МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "DSENM",
      Lang.ru: "ДСЭНМ",
      Lang.en: "Sanitary-epidemiological service",
    }, Icons.health_and_safety_outlined, [
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "23.07.2026", "Yangiyo'l shahar", "город Янгиюль"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "24.07.2026", "A.Yassaviy MFY", "А.Яссавий МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "04.08.2026", "Quyosh MFY", "Қуёш МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "11.08.2026", "Navoiy MFY", "Навоий МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "13.08.2026", "Obod MFY", "Обод МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "18.08.2026", "Bo'ston MFY", "Бўстон МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "18.08.2026", "Kamolot MFY", "Камолот МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "20.08.2026", "Bekobod tumani", "Бекабадский район"),
      SayyorVisit("Piskent tumani", "Пскентский район", "20.08.2026", "Do'ngqo'rg'on MFY", "Дўнгқўрғон МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "07.09.2026", "Mustaqillik MFY", "Мустақиллик МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "08.09.2026", "Turon MFY", "Турон МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "10.09.2026", "Bo'stonliq tumani", "Бостанлыкский район"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "10.09.2026", "Ma'rifat MFY", "Маърифат МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "10.09.2026", "Namuna MFY", "Намуна МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "16.09.2026", "Do'stlik MFY", "Дўстлик МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "22.09.2026", "Navro'z MFY", "Наврўз МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Sog'liqni saqlash",
      Lang.ru: "Здравоохранение",
      Lang.en: "Healthcare",
    }, Icons.local_hospital_outlined, [
      SayyorVisit("Bo'ka tumani", "Букинский район", "24.07.2026", "Moytepa MFY", "Мойтепа МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "24.07.2026", "Qo'shtepa MFY", "Қўштепа МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "24.07.2026", "Kensoy MFY", "Кенсой МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "30.07.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "31.07.2026", "Zangiota tumani", "Зангиатинский район"),
      SayyorVisit("Bo'ka tumani", "Букинский район", "31.07.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "07.08.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "13.08.2026", "Oppoq MFY", "Оппоқ МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "20.08.2026", "Xasanboy MFY", "Хасанбой МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "21.08.2026", "Mustaqillik MFY", "Мустақиллик МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "27.08.2026", "Evalak MFY", "Эвалак МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "10.09.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "11.09.2026", "S.Raximov MFY", "С.Рахимов МФЙ"),
      SayyorVisit("Toshkent tumani", "Ташкентский район", "22.09.2026", "Oltintepa MFY", "Олтинтепа МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "24.09.2026", "Navro'z MFY", "Наврўз МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "25.09.2026", "Usta Normat MFY", "Уста Нормат МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Hokimiyat",
      Lang.ru: "Хокимият",
      Lang.en: "Governor's office",
    }, Icons.apartment, [
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "29.07.2026", "Chimgan MFY", "Чимган МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "30.07.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "06.08.2026", "Xumson MFY", "Хумсон МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "12.08.2026", "Gulobod, Boyterak MFY", "Гулобод, Бойтерак МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "13.08.2026", "Chirchiq shahar", "город Чирчик"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "13.08.2026", "Oppoq MFY", "Оппоқ МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "26.08.2026", "Toshkent tumani", "Ташкентский район"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "26.08.2026", "Qo'shqo'rg'on, Xo'jaobod MFY", "Қўшқўрғон, Хўжаобод МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "27.08.2026", "Evalak MFY", "Эвалак МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "09.09.2026", "Birlik, Kichiksoy MFY", "Бирлик, Кичиксой МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "10.09.2026", "Angren shahar", "город Ангрен"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "10.09.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "22.09.2026", "Yangiyo'l tumani", "Янгиюльский район"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "23.09.2026", "Qapal, Beshtut MFY", "Қапал, Бештут МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "24.09.2026", "Navro'z MFY", "Наврўз МФЙ"),
      SayyorVisit("Bo'stonliq tumani", "Бостанлыкский район", "29.09.2026", "S.Xondoyliqiy, Ko'kto'nli MFY", "С.Хондойлиқий, Кўктўнли МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Soliq",
      Lang.ru: "Налоговая служба",
      Lang.en: "Tax service",
    }, Icons.receipt_long_outlined, [
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "24.07.2026", "Yoshlik MFY", "Ёшлик МФЙ"),
      SayyorVisit("Quyi Chirchiq tumani", "Куйичирчикский район", "24.07.2026", "Paxtachi MFY", "Пахтачи МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "30.07.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "07.08.2026", "Qo'rg'oncha MFY", "Қўрғонча МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "13.08.2026", "Oppoq MFY", "Оппоқ МФЙ"),
      SayyorVisit("Quyi Chirchiq tumani", "Куйичирчикский район", "14.08.2026", "Navqiron MFY", "Навқирон МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "21.08.2026", "Boyguli MFY", "Бойгули МФЙ"),
      SayyorVisit("Quyi Chirchiq tumani", "Куйичирчикский район", "26.08.2026", "Tinchlik MFY", "Тинчлик МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "27.08.2026", "Evalak MFY", "Эвалак МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "10.09.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "11.09.2026", "Sultonobod MFY", "Султонобод МФЙ"),
      SayyorVisit("Quyi Chirchiq tumani", "Куйичирчикский район", "16.09.2026", "Mashrab MFY", "Машраб МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "18.09.2026", "Jag'alboyli MFY", "Жағалбойли МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "24.09.2026", "Navro'z MFY", "Наврўз МФЙ"),
      SayyorVisit("Quyi Chirchiq tumani", "Куйичирчикский район", "25.09.2026", "Vatan MFY", "Ватан МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Elektr ta'minoti",
      Lang.ru: "Электроснабжение",
      Lang.en: "Electricity supply",
    }, Icons.bolt, [
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "24.07.2026", "Qo'rg'on MFY", "Қўрғон МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "29.07.2026", "Ohangaron tumani", "Ахангаранский район"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "30.07.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "12.08.2026", "Ohangaron shahar", "город Ахангаран"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "13.08.2026", "Oppoq MFY", "Оппоқ МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "21.08.2026", "Orzu MFY", "Орзу МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "26.08.2026", "Piskent tumani", "Пскентский район"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "27.08.2026", "Evalak MFY", "Эвалак МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "10.09.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "16.09.2026", "O'rta Chirchiq tumani", "Уртачирчикский район"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "22.09.2026", "Adolat MFY", "Адолат МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "23.09.2026", "Nurafshon shahar", "город Нурафшон"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "24.09.2026", "Navro'z MFY", "Наврўз МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Prokuratura",
      Lang.ru: "Прокуратура",
      Lang.en: "Prosecutor's office",
    }, Icons.gavel, [
      SayyorVisit("Bekobod shahar", "город Бекабад", "30.07.2026", "Qosim ota Farmonov MFY", "Қосим ота Фармонов МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "31.07.2026", "Qo'shtepa MFY", "Қўштепа МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "13.08.2026", "Yangiyo'l tumani", "Янгиюльский район"),
      SayyorVisit("Bekobod shahar", "город Бекабад", "14.08.2026", "Birdamlik MFY", "Бирдамлик МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "14.08.2026", "Qo'rg'ona MFY", "Қўрғона МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "28.08.2026", "Tortuvli MFY", "Тортувли МФЙ"),
      SayyorVisit("Bekobod shahar", "город Бекабад", "31.08.2026", "Turkiston MFY", "Туркистон МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "10.09.2026", "O'rta Chirchiq tumani", "Уртачирчикский район"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "11.09.2026", "Boyguli MFY", "Бойгули МФЙ"),
      SayyorVisit("Bekobod shahar", "город Бекабад", "15.09.2026", "Shirin MFY", "Ширин МФЙ"),
      SayyorVisit("Yangiyo'l tumani", "Янгиюльский район", "23.09.2026", "Niyozbosh MFY", "Ниёзбош МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "25.09.2026", "Eltamg'ali MFY", "Элтамғали МФЙ"),
      SayyorVisit("Bekobod shahar", "город Бекабад", "30.09.2026", "Ma'rifat MFY", "Маърифат МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Mahallalar uyushmasi",
      Lang.ru: "Ассоциация махаллей",
      Lang.en: "Mahalla association",
    }, Icons.holiday_village_outlined, [
      SayyorVisit("Chinoz tumani", "Чиназский район", "28.07.2026", "Madaniyat MFY", "Маданият МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "30.07.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Bekobod shahar", "город Бекабад", "31.07.2026", "Navro'z MFY", "Наврўз МФЙ"),
      SayyorVisit("Bekobod shahar", "город Бекабад", "11.08.2026", "Sayxun MFY", "Сайхун МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "13.08.2026", "Oppoq MFY", "Оппоқ МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "15.08.2026", "Axillik MFY", "Ахиллик МФЙ"),
      SayyorVisit("Bekobod shahar", "город Бекабад", "25.08.2026", "Bobur MFY", "Бобур МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "27.08.2026", "Evalak MFY", "Эвалак МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "29.08.2026", "Amir Temur MFY", "Амир Темур МФЙ"),
      SayyorVisit("Bekobod shahar", "город Бекабад", "08.09.2026", "Nurli yo'l MFY", "Нурли йўл МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "10.09.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Bekobod shahar", "город Бекабад", "22.09.2026", "Tsementchi MFY", "Цементчи МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "24.09.2026", "Navro'z MFY", "Наврўз МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Gaz ta'minoti",
      Lang.ru: "Газоснабжение",
      Lang.en: "Gas supply",
    }, Icons.local_fire_department_outlined, [
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "24.07.2026", "Yuksalish MFY", "Юксалиш МФЙ"),
      SayyorVisit("Olmaliq shahar", "город Алмалык", "03.08.2026", "A.Qaxxor MFY", "А.Қаххор МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "05.08.2026", "Tortuvli MFY", "Тортувли МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "14.08.2026", "Oppoq MFY", "Оппоқ МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "17.08.2026", "Jag'alboyli MFY", "Жағалбойли МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "19.08.2026", "Adolat MFY", "Адолат МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "27.08.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "08.09.2026", "Tolovul MFY", "Толовул МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "11.09.2026", "Evalak MFY", "Эвалак МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "14.09.2026", "Zarbdor MFY", "Зарбдор МФЙ"),
      SayyorVisit("Olmaliq shahar", "город Алмалык", "15.09.2026", "U.Nosir MFY", "У.Носир МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "18.09.2026", "Bo'ston MFY", "Бўстон МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "25.09.2026", "Obod MFY", "Обод МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Suv ta'minoti",
      Lang.ru: "Водоснабжение",
      Lang.en: "Water supply",
    }, Icons.water_drop_outlined, [
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "22.07.2026", "Orzu MFY", "Орзу МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "29.07.2026", "Oppoq MFY", "Оппоқ МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "04.08.2026", "Chirchiq shahar", "город Чирчик"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "12.08.2026", "Evalak MFY", "Эвалак МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "20.08.2026", "Guliston MFY", "Гулистон МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "25.08.2026", "Qibray tuman", "Қибрай туман"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "26.08.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "08.09.2026", "Ohangaron shahar", "город Ахангаран"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "09.09.2026", "Navro'z MFY", "Наврўз МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "15.09.2026", "Shodlik MFY", "Шодлик МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "23.09.2026", "Bekobod tumani", "Бекабадский район"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "23.09.2026", "Taraqqiyot MFY", "Тараққиёт МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Kadastr agentligi",
      Lang.ru: "Кадастровое агентство",
      Lang.en: "Cadastre agency",
    }, Icons.map_outlined, [
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "25.07.2026", "Oybuloq MFY", "Ойбулоқ МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "30.07.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "13.08.2026", "Oppoq MFY", "Оппоқ МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "19.08.2026", "Qo'rg'on MFY", "Қўрғон МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "27.08.2026", "Evalak MFY", "Эвалак МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "27.08.2026", "Shodmalik MFY", "Шодмалик МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "10.09.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "23.09.2026", "Xonobod MFY", "Хонобод МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "24.09.2026", "Navro'z MFY", "Наврўз МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "24.09.2026", "Nurobod MFY", "Нуробод МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Madaniyat",
      Lang.ru: "Культура",
      Lang.en: "Culture",
    }, Icons.theater_comedy_outlined, [
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "Iyul", "Chirchiq shahar", "город Чирчик"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "Iyul", "Qibray tumani", "Кибрайский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "Iyul", "Chirchiq shahar", "город Чирчик"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "Avgust", "Ohangaron tumani", "Ахангаранский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "Avgust", "Ohangaron tumani", "Ахангаранский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "Avgust", "Toshkent tumani", "Ташкентский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "Sentabr", "Yangiyo'l shahar", "город Янгиюль"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "Sentabr", "Bo'ka tumani", "Букинский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "Sentabr", "Bo'stonliq tumani", "Бостанлыкский район"),
    ]),
    SayyorOrg({
      Lang.uz: "Agrobank",
      Lang.ru: "Агробанк",
      Lang.en: "Agrobank",
    }, Icons.account_balance_outlined, [
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "24.07.2026", "Navoiy MFY", "Навоий МФЙ"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "14.08.2026", "Jaloltepa MFY", "Жалолтепа МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "17.08.2026", "Bo'ka tumani", "Букинский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "18.08.2026", "Quyi Chirchiq tumani", "Куйичирчикский район"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "21.08.2026", "Jumabozor MFY", "Жумабозор МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "15.09.2026", "Ohangaron tumani", "Ахангаранский район"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "15.09.2026", "Darxan MFY", "Дархан МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "16.09.2026", "Bekobod tumani", "Бекабадский район"),
      SayyorVisit("Yuqori Chirchiq tumani", "Юкоричирчикский район", "25.09.2026", "Yangixayot MFY", "Янгихаёт МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Xotin-qizlar",
      Lang.ru: "Комитет женщин",
      Lang.en: "Women's committee",
    }, Icons.diversity_3_outlined, [
      SayyorVisit("Angren shahar", "город Ангрен", "22.07.2026", "Obliq MFY", "Облиқ МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "12.08.2026", "Qorabog' MFY", "Қорабоғ МФЙ"),
      SayyorVisit("Yangiyo'l shahri", "город Янгиюль", "18.08.2026", "Yangibog' MFY", "Янгибоғ МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "19.08.2026", "Samarchuq MFY", "Самарчуқ МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "26.08.2026", "Oppartak MFY", "Оппартак МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "02.09.2026", "Kimyogar MFY", "Кимёгар МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "16.09.2026", "G'ofur G'ulom MFY", "Ғофур Ғулом МФЙ"),
      SayyorVisit("Yangiyo'l shahri", "город Янгиюль", "22.09.2026", "Olmos MFY", "Олмос МФЙ"),
      SayyorVisit("Angren shahar", "город Ангрен", "30.09.2026", "Bo'ston MFY", "Бўстон МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Kadastr palatasi",
      Lang.ru: "Кадастровая палата",
      Lang.en: "Cadastre chamber",
    }, Icons.layers_outlined, [
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "23.07.2026", "Bo'stonliq tumani", "Бостанлыкский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "13.08.2026", "Chirchiq shahar", "город Чирчик"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "20.08.2026", "Qibray tuman", "Қибрай туман"),
      SayyorVisit("Piskent tumani", "Пскентский район", "21.08.2026", "Mingtepa MFY", "Мингтепа МФЙ"),
      SayyorVisit("Piskent tumani", "Пскентский район", "14.09.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "17.09.2026", "Yuqori Chirchiq tumani", "Юкоричирчикский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "24.09.2026", "Bo'ka tumani", "Букинский район"),
    ]),
    SayyorOrg({
      Lang.uz: "Obodonlashtirish",
      Lang.ru: "Благоустройство",
      Lang.en: "Landscaping service",
    }, Icons.park_outlined, [
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "30.07.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "11.08.2026", "Nurobod MFY", "Нуробод МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "13.08.2026", "Oppoq MFY", "Оппоқ МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "27.08.2026", "Evalak MFY", "Эвалак МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "10.09.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Ohangaron tumani", "Ахангаранский район", "22.09.2026", "Tut MFY", "Тут МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "24.09.2026", "Navro'z MFY", "Наврўз МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Kambag'allikni qisqartirish va bandlik",
      Lang.ru: "Сокращение бедности и занятость",
      Lang.en: "Poverty reduction and employment",
    }, Icons.work_outline, [
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "28.07.2026", "Orzu MFY", "Орзу МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "20.08.2026", "Xonobod MFY", "Хонобод МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "24.08.2026", "Qo'shtepa, X.Olimjon MFY", "Қўштепа, Х.Олимжон МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "10.09.2026", "No'g'oyqo'rg'on MFY", "Нўғойқўрғон МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "21.09.2026", "Tortuvli, Boyguli MFY", "Тортувли, Бойгули МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "23.09.2026", "Navbaxor MFY", "Навбахор МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Raqobat",
      Lang.ru: "Комитет по конкуренции",
      Lang.en: "Competition committee",
    }, Icons.balance, [
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "24.07.2026", "Bo'stonliq tumani", "Бостанлыкский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "24.07.2026", "Chirchiq shahar", "город Чирчик"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "20.08.2026", "Qibray tuman", "Қибрай туман"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "20.08.2026", "Toshkent tumani", "Ташкентский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "16.09.2026", "Zangiota tumani", "Зангиатинский район"),
    ]),
    SayyorOrg({
      Lang.uz: "Majburiy ijro byurosi",
      Lang.ru: "Бюро принудительного исполнения",
      Lang.en: "Compulsory Enforcement Bureau",
    }, Icons.assignment_turned_in_outlined, [
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "30.07.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "13.08.2026", "Oppoq MFY", "Оппоқ МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "27.08.2026", "Evalak MFY", "Эвалак МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "10.09.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "24.09.2026", "Navro'z MFY", "Наврўз МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "IIB",
      Lang.ru: "ОВД",
      Lang.en: "Internal affairs (IIB)",
    }, Icons.local_police_outlined, [
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "30.07.2026", "Yangiobod MFY", "Янгиобод МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "13.08.2026", "Oppoq MFY", "Оппоқ МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "27.08.2026", "Evalak MFY", "Эвалак МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "10.09.2026", "Birlik MFY", "Бирлик МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "24.09.2026", "Navro'z MFY", "Наврўз МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Sport",
      Lang.ru: "Спорт",
      Lang.en: "Sports",
    }, Icons.sports_soccer, [
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "25.07.2026", "Olmaliq shahar", "город Алмалык"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "21.08.2026", "Piskent tumani", "Пскентский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "09.09.2026", "Bo'ka tumani", "Букинский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "26.09.2026", "Oqqo'rg'on tumani", "Аккурганский район"),
    ]),
    SayyorOrg({
      Lang.uz: "Transport",
      Lang.ru: "Транспорт",
      Lang.en: "Transport",
    }, Icons.directions_bus_outlined, [
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "Iyul", "Bo'stonliq tumani", "Бостанлыкский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "Avgust", "Ohangaron tumani", "Ахангаранский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "Sentabr", "Toshkent tumani", "Ташкентский район"),
    ]),
    SayyorOrg({
      Lang.uz: "Avtoyo'l",
      Lang.ru: "Автомобильные дороги",
      Lang.en: "Highways service",
    }, Icons.edit_road, [
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "22.07.2026", "Guliston MFY", "Гулистон МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "11.08.2026", "Sultonobod MFY", "Султонобод МФЙ"),
      SayyorVisit("Oqqo'rg'on tumani", "Аккурганский район", "14.09.2026", "Xonobod MFY", "Хонобод МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Issiqlik ta'minoti",
      Lang.ru: "Теплоснабжение",
      Lang.en: "Heat supply",
    }, Icons.thermostat, [
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "13.08.2026", "Toshkent tumani", "Ташкентский район"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "15.09.2026", "Ohangaron tumani", "Ахангаранский район"),
    ]),
    SayyorOrg({
      Lang.uz: "Turizm boshqarmasi",
      Lang.ru: "Управление туризма",
      Lang.en: "Tourism department",
    }, Icons.travel_explore, [
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "20.08.2026", "Angren shahar", "город Ангрен"),
      SayyorVisit("Viloyat tashkilotlari", "Областные организации", "15.09.2026", "Zangiota tumani", "Зангиатинский район"),
    ]),
    SayyorOrg({
      Lang.uz: "Veterinariya",
      Lang.ru: "Ветеринария",
      Lang.en: "Veterinary service",
    }, Icons.pets_outlined, [
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "13.08.2026", "Obod MFY", "Обод МФЙ"),
      SayyorVisit("Nurafshon shahar", "город Нурафшон", "10.09.2026", "Ma'rifat MFY", "Маърифат МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Qurilish va uy-joy kommunal xo'jaligi",
      Lang.ru: "Строительство и ЖКХ",
      Lang.en: "Construction and housing utilities",
    }, Icons.home_work_outlined, [
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "21.08.2026", "No'g'oyqo'rg'on MFY", "Нўғойқўрғон МФЙ"),
      SayyorVisit("Ohangaron shahar", "город Ахангаран", "10.09.2026", "Yangilik MFY", "Янгилик МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Xalq banki",
      Lang.ru: "Народный банк",
      Lang.en: "Xalq Bank",
    }, Icons.account_balance_wallet_outlined, [
      SayyorVisit("Chinoz tumani", "Чиназский район", "05.08.2026", "Sutbuloq MFY", "Сутбулоқ МФЙ"),
      SayyorVisit("Chinoz tumani", "Чиназский район", "14.09.2026", "Rasulobod MFY", "Расулобод МФЙ"),
    ]),
    SayyorOrg({
      Lang.uz: "Chirchiq davlat tibbiyot universiteti",
      Lang.ru: "Чирчикский государственный медицинский университет",
      Lang.en: "Chirchiq State Medical University",
    }, Icons.school_outlined, [
      SayyorVisit("Chirchiq shahar", "город Чирчик", "20.08.2026", "A.Temur, Adolat MFY", "А.Темур, Адолат МФЙ"),
      SayyorVisit("Chirchiq shahar", "город Чирчик", "10.09.2026", "Shodlik, Kimyogar MFY", "Шодлик, Кимёгар МФЙ"),
    ]),
  ];
}
